name: Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64, executable: AssetRipper.GUI.Free.exe }
          - { name: win_arm64, os: windows-latest, runtime: win-arm64, executable: AssetRipper.GUI.Free.exe }
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper.GUI.Free/
      - name: List Files
        shell: bash
        run: ls -R ./Source/0Bins/AssetRipper.GUI.Free/Release/
      - name: List Files
        shell: bash
        run: date -u > ./Source/0Bins/AssetRipper.GUI.Free/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AssetRipper_${{ matrix.config.name }}
          path: |
            ./Source/0Bins/AssetRipper.GUI.Free/Release/${{ matrix.config.runtime }}/publish/${{ matrix.config.executable }}
            ./Source/0Bins/AssetRipper.GUI.Free/Release/${{ matrix.config.runtime }}/publish/*.dll
            ./Source/0Bins/AssetRipper.GUI.Free/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
          if-no-files-found: error
